### ISSUE TITLE
Describe, how to register you own types in class map

### ISSUE THREAD

**Issue by alexvaluyskiy** [AkkaNetContrib/Akka.Persistence.MongoDB#22]
http://api.mongodb.com/csharp/2.1/html/M_MongoDB_Bson_Serialization_BsonClassMap_RegisterClassMap__1_1.htm

**Comment by spankr** [comment]
In order to use the MongoDB persistence, I have to register my each of my events using BsonClassMap.

Would it be a reasonable request to have that internal to the MongoDB persistence? As everything we pass to Persist would get its type registered with the BsonClassMap.

That way our applications aren't tightly coupled to MongoDB. (In case we want to use a different persistence implementation.)

**Comment by jackowild** [comment]
Solved by #28
